### ISSUE TITLE
error: could not detect network

### ISSUE THREAD

**Issue by entin-hun** [TheBojda/nft_minter#1]
yarn run v1.22.22
warning ../../package.json: No license field
$ ts-node src/app.ts
Server is running on http://localhost:3000

> aaand when minting {"to": "0x70997970C51812dc3A010C7d01b50e0d17dc79C8", "uri": "https://api.gateway.ethswarm.org/bzz/d549b12c1be0562e5ee9c8415d0bde8aff48e9cb593cb7277b81c24a58b5dc15"}

Error minting NFT: Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
    at Logger.makeError (/Users/mac-pro/Downloads/nft_minter/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/Users/mac-pro/Downloads/nft_minter/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at JsonRpcProvider.<anonymous> (/Users/mac-pro/Downloads/nft_minter/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:483:23)
    at step (/Users/mac-pro/Downloads/nft_minter/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/Users/mac-pro/Downloads/nft_minter/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/Users/mac-pro/Downloads/nft_minter/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}

**Comment by TheBojda** [comment]
Run the hardhat test node in another terminal window.

From the README:
```
npx hardhat node (in a separated terminal)
```

**Comment by entin-hun** [comment]
yes, I've done all the steps, in 3 tabs. Maybe **eth_maxPriorityFeePerGas - Method not supported** is the issue..
<img width="741" alt="image" src="https://github.com/TheBojda/nft_minter/assets/50300541/3bf96896-35b6-4ed5-a212-e3ce716a28f8">

**Comment by TheBojda** [comment]
It is a warning only, skip it. As you see the next green line, the transaction is mined successfully.
